# Generated by Django 3.2.9 on 2021-11-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopUsers', '0002_category_comment_emailtocustomer_emailtosupplier_order_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopUsers.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopUsers.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopUsers.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favourit_user_product',
            field=models.ManyToManyField(blank=True, to='shopUsers.User'),
        ),
    ]
