# Generated by Django 3.2.9 on 2021-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0002_auto_20211115_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
